### PR TITLE
chore: Create account-abstraction.mdx

### PR DESCRIPTION
**Pull request by raymond2338**

### CODE REVIEW

**Comment by shunkakinoki** [comment]
Do you want to merge this into chain abstraction? 

`chain abstraction` may be the narrative we're looking for, rather than people thinking we're just an `account abstraction` wallet

**Comment by raymond2338** [comment]
> Do you mind if we merge this into chain abstraction?
> 
> `chain abstraction` may be the narrative we're looking for, rather than people thinking we're just an `account abstraction` wallet
> 
> Would love your thoughts

agreed very much so. Will make that update when i get the chance

**Comment by raymond2338** [comment]
> > Do you mind if we merge this into chain abstraction?
> > `chain abstraction` may be the narrative we're looking for, rather than people thinking we're just an `account abstraction` wallet
> > Would love your thoughts
> 
> agreed very much so. Will make that update when i get the chance

new PR: https://github.com/LightDotSo/LightDotSo/pull/1885

**Comment by shunkakinoki** [comment]
should i close?

**Comment by shunkakinoki** [comment]
closing in favor of https://github.com/LightDotSo/LightDotSo/pull/1885

**Pull request closed without merging**
